### ISSUE TITLE
Please provide steps after Running the server

### ISSUE THREAD

**Issue by swaroop-jambhulkar** [ujjwalkrishna/ProductFi#1]
Can you please share the steps after Running the server: node server.js
and how to configure mysql database cause I am getting errors 

C:\Users\micro\OneDrive\Desktop\ProductFi-master\server_side> node server.js
express-session deprecated req.secret; provide secret option server.js:29:9
Talking with a geth server 0.20.1

Listening to port 8080...

Connected to MySql!

And after going to the localhost:8080 i get this error:

Error: secret option required for sessions
    at session (C:\Users\micro\OneDrive\Desktop\ProductFi-master\server_side\node_modules\express-session\index.js:199:12)
    at Layer.handle [as handle_request] (C:\Users\micro\OneDrive\Desktop\ProductFi-master\server_side\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\micro\OneDrive\Desktop\ProductFi-master\server_side\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\micro\OneDrive\Desktop\ProductFi-master\server_side\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\micro\OneDrive\Desktop\ProductFi-master\server_side\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\micro\OneDrive\Desktop\ProductFi-master\server_side\node_modules\express\lib\router\index.js:275:10)
    at urlencodedParser (C:\Users\micro\OneDrive\Desktop\ProductFi-master\server_side\node_modules\body-parser\lib\types\urlencoded.js:91:7)
    at Layer.handle [as handle_request] (C:\Users\micro\OneDrive\Desktop\ProductFi-master\server_side\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\micro\OneDrive\Desktop\ProductFi-master\server_side\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\micro\OneDrive\Desktop\ProductFi-master\server_side\node_modules\express\lib\router\index.js:284:7

please provide the solution.

**Comment by ujjwalkrishna** [comment]
In .env file you need to add these variables:

database_user=`{your_db_username`}
database_password=`{your_db_pass}`
secret=`{cookie_secret(anything you want)}`
address=`{address of your ethereum network created on ganache}`
